-------------------------------------------------
-- 1–10: Basic Business Insights
-------------------------------------------------
-- 1. How many customers are there in each state?
SELECT customer_state , COUNT(customer_id) AS customers FROM customers
GROUP BY customer_state
ORDER BY customers DESC;
-- SP STATE HAS HIGHEST CUSTOMER SHARE
"SP"	41746
"RJ"	12852
"MG"	11635

-- Which 10 cities have the highest number of customers?
SELECT customer_city , COUNT(customer_id) AS customers FROM customers
GROUP BY customer_city
ORDER BY customers DESC
LIMIT 10;
"sao paulo"	15540
"rio de janeiro"	6882
"belo horizonte"	2773
"brasilia"	2131
"curitiba"	1521
"campinas"	1444
"porto alegre"	1379
"salvador"	1245
"guarulhos"	1189
"sao bernardo do campo"	938

-- How many orders were placed each month?
SELECT TO_CHAR(order_purchase_timestamp,'YYYY-MM') AS month ,COUNT(order_id) AS orders 
FROM orders
GROUP BY month
ORDER BY month;
"2016-09"	4
"2016-10"	324
"2016-12"	1
"2017-01"	800
"2017-02"	1780
"2017-03"	2682
...

-- Find the distribution of order statuses.
SELECT order_status , count(*) AS order FROM orders
GROUP BY order_status;
"shipped"	1107
"unavailable"	609
"invoiced"	314
"created"	5
"approved"	2
"processing"	301
"delivered"	96478
"canceled"	625

-- What is the average order value?
SELECT ROUND(AVG(ord_val),2) 
FROM (
	SELECT order_id , SUM(price) AS ord_val FROM order_items
	GROUP BY 1 );
137.75

-- Which payment method is used most frequently?
SELECT payment_type , COUNT(order_id) cnt FROM order_payments
GROUP BY payment_type
ORDER BY cnt DESC;
"credit_card"	76795
"boleto"	19784
"voucher"	5769
"debit_card"	1529

-- Which seller has sold the highest number of products?
SELECT seller_id , COUNT(*) AS sold FROM order_items
GROUP BY seller_id
ORDER BY sold DESC;
"6560211a19b47992c3666cc44a7e94c0"	2033
"4a3ca9315b744ce9f8e9374361493884"	1987
"1f50f920176fa81dab994f9023523100"	1931
"cc419e0650a3c5ba77189a1882b7556a"	1775
"da8622b14eb17ae2831f4ac5b9dab84a"	1551

-- Which product categories have the most products?
SELECT t.product_category_name_english , COUNT(p.product_id) AS prods FROM products p
INNER JOIN product_category_translation t
	ON p.product_category_name = t.product_category_name
GROUP BY 1
ORDER BY 2 DESC;
"bed_bath_table"	3029
"sports_leisure"	2867

-- Find the earliest and latest purchase dates.
SELECT 
	MIN(order_purchase_timestamp) AS earliest ,
	MAX(order_purchase_timestamp) AS latest
FROM orders;
"2016-09-04 21:15:19"	"2018-10-17 17:30:18"

-- Which states have the highest average payment value?
WITH payments AS(
SELECT o.order_id , SUM(payment_value) AS ord_pay FROM orders o
INNER JOIN order_payments p
ON o.order_id = p.order_id
GROUP BY o.order_id
)
SELECT customer_state ,ROUND(AVG(ord_pay),2) FROM payments p
INNER JOIN orders o
	ON p.order_id = o.order_id
INNER JOIN customers c
	ON o.customer_id = c.customer_id
GROUP BY 1
ORDER BY 2 DESC;
"PB"	264.08

---------------------------------------------------------
-- 11–20: Sales & Revenue Analysis
---------------------------------------------------------

-- Calculate total revenue generated by each seller.
SELECT seller_id , SUM(price) AS sales FROM order_items
GROUP BY seller_id
ORDER BY 2 DESC;

-- Find the top 10 sellers by revenue.
SELECT seller_id , SUM(price) AS sales FROM order_items
GROUP BY seller_id
ORDER BY 2 DESC
LIMIT 10;
"4869f7a5dfa277a7dca6462dcf3b52b2"	229472.63
"53243585a1d6dc2643021fd1853d8905"	222776.05
"4a3ca9315b744ce9f8e9374361493884"	200472.92...

-- Find the top 10 product categories by revenue.
SELECT product_category_name_english , SUM(price) AS revenue FROM order_items i
INNER JOIN products p
	ON i.product_id = p.product_id
INNER JOIN product_category_translation t
	ON p.product_category_name = t.product_category_name
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;
"health_beauty"	1258681.34
"watches_gifts"	1205005.68
"bed_bath_table"	1036988.68
"sports_leisure"	988048.97
"computers_accessories"	911954.32
"furniture_decor"	729762.49
"cool_stuff"	635290.85
"housewares"	632248.66
"auto"	592720.11
"garden_tools"	485256.46

-- Calculate the average order value for each state.

WITH order_value AS (
SELECT order_id, SUM(price) AS ord_val FROM order_items
GROUP BY order_id
)
SELECT customer_state , ROUND(AVG(ord_val),2) AS avg_ord_val
FROM order_value v
INNER JOIN orders o
	ON o.order_id = v.order_id
INNER JOIN customers c
	ON c.customer_id = o.customer_id
GROUP BY 1
ORDER BY 2 DESC;


-- Which products generated the highest revenue?
SELECT product_id , SUM(price) AS revenue FROM order_items
GROUP BY 1
ORDER BY 2 DESC;

-- Which orders have the highest freight cost?
SELECT order_id , SUM(freight_value) AS freight_cost FROM order_items
GROUP BY 1
ORDER BY 2 DESC;

-- Calculate total freight collected by each seller.
SELECT seller_id , SUM(freight_value) AS freight_cost FROM order_items
GROUP BY 1
ORDER BY 2 DESC;

-- Find categories where average product price exceeds the overall average.
SELECT product_category_name_english ,AVG(price) AS cate_avg FROM order_items i
INNER JOIN products p
	ON p.product_id = i.product_id
INNER JOIN product_category_translation t
	ON p.product_category_name = t.product_category_name
GROUP BY 1
HAVING  AVG(price) > (SELECT AVG(price) FROM order_items)
ORDER BY 2 DESC;

-- Calculate monthly revenue trends.
SELECT TO_CHAR(order_purchase_timestamp,'YYYY-MM') AS month ,SUM(payment_value) AS revenue FROM orders o
INNER JOIN order_payments p
ON o.order_id = p.order_id
GROUP BY month
ORDER BY month;

-- Find the percentage contribution of each payment type to total revenue.
SELECT 
	payment_type , 
	ROUND(SUM(payment_value)/(SELECT SUM(payment_value) FROM order_payments),2)*100 AS contribution 
FROM order_payments
GROUP BY payment_type ;

---------------------------------------------------------
-- 21–30: Customer Analysis
---------------------------------------------------------
-- Find customers who placed more than five orders.
SELECT customer_unique_id , COUNT(order_id) AS orders FROM orders o
INNER JOIN customers c
ON c.customer_id = o.customer_id
GROUP BY customer_unique_id
HAVING COUNT(order_id) > 5
ORDER BY 2 DESC;

-- Find customers who never placed an order.
SELECT customer_unique_id FROM customers c
WHERE customer_id NOT IN (SELECT customer_id FROM orders);

-- Find customers who purchased from more than one seller.
SELECT 
	customer_unique_id,
	COUNT(DISTINCT seller_id) purchase_seller_cnt 
FROM customers c
INNER JOIN orders o
ON o.customer_id = c.customer_id
INNER JOIN order_items i
ON o.order_id = i.order_id
GROUP BY 1
HAVING COUNT(DISTINCT seller_id) >1
ORDER BY 2 DESC;

-- Find customers who spent more than the average customer.

WITH cust_spends AS (
    SELECT customer_unique_id, SUM(payment_value) AS spending
    FROM customers c
    INNER JOIN orders o ON o.customer_id = c.customer_id
    INNER JOIN order_payments p ON o.order_id = p.order_id
    GROUP BY customer_unique_id
)
SELECT customer_unique_id, spending
FROM cust_spends
WHERE spending > (SELECT AVG(spending) FROM cust_spends)
ORDER BY spending DESC;

-- Find the top 20 customers by total spending.
SELECT customer_unique_id, SUM(payment_value) AS total_spending FROM customers c
INNER JOIN orders o
ON o.customer_id = c.customer_id
INNER JOIN order_payments p
ON o.order_id = p.order_id
GROUP BY customer_unique_id
ORDER BY 2 DESC
LIMIT 20;

-- Calculate the average spending per customer by state.
WITH cust_spends AS (
SELECT customer_unique_id,customer_state, SUM(payment_value) AS spending FROM customers c
INNER JOIN orders o
ON o.customer_id = c.customer_id
INNER JOIN order_payments p
ON o.order_id = p.order_id
GROUP BY customer_unique_id , customer_state
)
SELECT customer_state, ROUND(AVG(spending),2) AS avg_spending FROM cust_spends
GROUP BY customer_state
ORDER BY 2 DESC;

-- Find customers who have only one order.
SELECT customer_unique_id, COUNT(order_id) AS order_cnt FROM customers c
INNER JOIN orders o
ON o.customer_id = c.customer_id
GROUP BY customer_unique_id
HAVING COUNT(order_id) = 1;

-- Rank customers based on total spending.
SELECT 
	RANK() OVER(ORDER BY  SUM(payment_value) DESC), 
	customer_unique_id, 
	SUM(payment_value) AS total_spending 
FROM customers c
INNER JOIN orders o
ON o.customer_id = c.customer_id
INNER JOIN order_payments p
ON o.order_id = p.order_id
GROUP BY customer_unique_id
ORDER BY 1;

-- Find customers who purchased products from multiple categories.
SELECT customer_unique_id, COUNT(DISTINCT product_category_name) AS cate_cnt FROM customers c
INNER JOIN orders o
ON o.customer_id = c.customer_id
INNER JOIN order_items i
ON o.order_id = i.order_id
INNER JOIN products p
ON i.product_id = p.product_id
GROUP BY customer_unique_id
HAVING COUNT(DISTINCT product_category_name) >1 
ORDER BY 2 DESC; 

-- Find repeat customers who ordered in multiple years.
SELECT customer_unique_id, COUNT(DISTINCT EXTRACT(YEAR FROM order_purchase_timestamp)) AS avg_spending FROM customers c
INNER JOIN orders o
ON o.customer_id = c.customer_id
GROUP BY customer_unique_id
HAVING COUNT(DISTINCT  EXTRACT(YEAR FROM order_purchase_timestamp)) > 1
ORDER BY 2 DESC;

------------------------------------------------------------
--31–40: Product & Seller Analysis
------------------------------------------------------------
-- Find products that were never sold.
SELECT product_id FROM products 
WHERE product_id NOT IN (SELECT product_id FROM order_items);

-- Find sellers with no sales.
SELECT seller_id FROM sellers 
WHERE seller_id NOT IN (SELECT seller_id FROM order_items);

-- Rank sellers by total revenue.
SELECT RANK() OVER(ORDER BY SUM(price) DESC), seller_id , SUM(price) AS total_revenue FROM order_items i
GROUP BY seller_id 
ORDER BY 1;

-- Find the top 3 sellers within each state.
SELECT * FROM (
SELECT seller_state , s.seller_id , RANK() OVER(PARTITION BY seller_state ORDER BY SUM(price) DESC) seller_rank
FROM sellers s
INNER JOIN order_items i
ON s.seller_id = i.seller_id
GROUP BY seller_state ,s.seller_id
ORDER BY 1,3)
WHERE seller_rank <=3;

-- Rank products within each category based on sales.
SELECT product_category_name , p.product_id , RANK() OVER(PARTITION BY product_category_name ORDER BY COUNT(i.product_id) DESC) FROM products p
INNER JOIN order_items i
ON p.product_id = i.product_id
GROUP BY product_category_name,p.product_id
ORDER BY 1,3;

-- Which sellers sell products in multiple categories?
SELECT i.seller_id , COUNT(DISTINCT product_category_name) FROM order_items i
INNER JOIN products p
ON i.product_id = p.product_id
GROUP BY seller_id
HAVING COUNT(DISTINCT product_category_name) >1
ORDER BY 2 DESC;

-- Find the average product price by category.
SELECT product_category_name_english , ROUND(AVG(price),2) cate_avg FROM products p
INNER JOIN order_items i
ON p.product_id = i.product_id
INNER JOIN product_category_translation t
ON p.product_category_name = t.product_category_name
GROUP BY product_category_name_english
ORDER BY 2 DESC;

-- Find categories having more than 1,000 products sold.
SELECT product_category_name_english , COUNT(i.product_id) prod_sold FROM products p
INNER JOIN order_items i
ON p.product_id = i.product_id
INNER JOIN product_category_translation t
ON p.product_category_name = t.product_category_name
GROUP BY product_category_name_english
HAVING COUNT(i.product_id) > 1000
ORDER BY 2 DESC;

-- Calculate each seller's contribution to company revenue.
SELECT 
	i.seller_id , 
	ROUND((SUM(price)/(SELECT SUM(price) FROM order_items))*100,2) AS contri_to_company
FROM order_items i
GROUP BY seller_id
ORDER BY 2 DESC;

-- Find sellers whose revenue is above the average seller revenue.
WITH seller_avg AS (
	SELECT seller_id , sum(price) as revenue 
	FROM order_items
	GROUP BY seller_id 
	)
SELECT * FROM seller_avg
WHERE revenue > (SELECT AVG(revenue) FROM seller_avg);

-------------------------------------------------------
-- 41–47: Advanced Business Case Studies
-------------------------------------------------------
-- Calculate the average delivery time for each seller.
SELECT 
	seller_id ,
	EXTRACT(DAY FROM AVG(order_delivered_customer_date-order_purchase_timestamp )) AS days 
FROM order_items i
INNER JOIN orders o
ON o.order_id = i.order_id
WHERE order_delivered_customer_date IS NOT NULL
GROUP BY seller_id
ORDER BY 2;

-- Find sellers with the fastest average delivery time.
SELECT 
	seller_id ,
	EXTRACT(DAY FROM AVG(order_delivered_customer_date-order_purchase_timestamp )) AS days 
FROM order_items i
INNER JOIN orders o
ON o.order_id = i.order_id
WHERE order_delivered_customer_date IS NOT NULL
GROUP BY seller_id
ORDER BY 2
LIMIT 10;

-- Calculate the percentage of late deliveries by state.
WITH late_order AS(
SELECT customer_state ,COUNT(*) AS late_delivered FROM customers c
INNER JOIN orders o
ON o.customer_id = c.customer_id
WHERE order_delivered_customer_date > order_estimated_delivery_date
GROUP BY customer_state
),
total_order AS(
SELECT customer_state , COUNT(DISTINCT order_id) AS total_delivered FROM customers c
INNER JOIN orders o
ON o.customer_id = c.customer_id
GROUP BY customer_state
)
SELECT  
	l.customer_state , 
	ROUND( 100.0*late_delivered/total_delivered ,2) AS late_delivery_percent
FROM late_order l
INNER JOIN total_order t
ON l.customer_state = t.customer_state
ORDER BY 2 DESC;



-- Find products with the highest average review score.
SELECT product_id , ROUND(AVG(review_score),1) avg_review_prod FROM order_items i
INNER JOIN order_reviews r
ON i.order_id = r.order_id
GROUP BY product_id
ORDER BY 2 DESC;

-- Find sellers whose average review score is below 3.
SELECT seller_id , ROUND(AVG(review_score),1) avg_review_seller FROM order_items i
INNER JOIN order_reviews r
ON r.order_id = i.order_id
GROUP BY 1
HAVING ROUND(AVG(review_score),1) < 3
ORDER BY 2;

-- Rank categories based on average customer ratings.
SELECT 
	DENSE_RANK() OVER(ORDER BY AVG(review_score) DESC),
	product_category_name ,
	ROUND(AVG(review_score),1) AS avg_rating
FROM products p
INNER JOIN order_items i
ON p.product_id = i.product_id
INNER JOIN order_reviews r
ON i.order_id = r.order_id
GROUP BY 2
ORDER BY 1 ;

-- Find the correlation between freight cost and delivery time
SELECT 
    ROUND(
        CORR(
            freight_value,
            EXTRACT(EPOCH FROM (order_delivered_customer_date - order_purchase_timestamp)) / 86400
        )::numeric, 3
    ) AS freight_delivery_correlation
FROM orders o
INNER JOIN order_items i
ON o.order_id = i.order_id
WHERE order_delivered_customer_date IS NOT NULL;

